### ISSUE TITLE
A popup click closes the frame without linking to the log

### ISSUE THREAD

**Issue by rchrand** [alcaras/mplus.subcreation.net#1]
Hi there, first of all, absolutely love the site and uses it all the time. One small bug I've encountered is trying to click a certain top log within a combination, but the window just closes instead of linking to the log. See the gif below

![subcreation-popup](https://user-images.githubusercontent.com/2136481/80370147-ca107b00-888f-11ea-8b5e-cf158de8241e.gif)

I've tried both in the latest Chrome and Firefox.

Thanks for your work!

**Comment by alcaras** [comment]
Thanks for the report!

Is the log opening in a new tab?

**Comment by rchrand** [comment]
It is not for me nor another window from what i can see. I've tried disabling ad-blockers and other extensions that normally modifies sites without luck.

**Comment by alcaras** [comment]
Hrm. It should open in a new tab, since there's a target="_blank" in the link.

Not sure what's going on -- able to inconsistently replicate this in Chrome, but it seems to depend on where I click on the link. I wonder what's causing this..

Can't replicate in Safari.

Thank you for flagging, will investigate.

In the meanwhile, I think you can right click on the link and choose "Open in New Tab" and it should work.

**Comment by alcaras** [comment]
Digging into this, looks like adding a delay will help: https://stackoverflow.com/questions/33117102/clicking-on-a-link-in-a-bootstrap-popover

Will test this and, if it works, implement. Thanks again for flagging!

**Comment by rchrand** [comment]
This is interesting, i can't even right-click on the link, as any click will make the frame go away. This is the case in both Firefox and Chrome on my PC. On my phone, it works fine.

**Comment by rchrand** [comment]
Thanks for looking into it!

**Comment by alcaras** [comment]
Am unable to replicate this now. Perhaps an underlying Bootstrap library got fixed. 

Please reopen if you're still seeing this.

**Comment by rchrand** [comment]
Thanks for looking into this. I'm still not able to click it, but i am able to capture the click with a right-click and open in a new tab, so that'll do for now.
