### ISSUE TITLE
Developer API

### ISSUE THREAD

**Issue by Wotuu** [alcaras/mplus.subcreation.net#10]
Hey!

A while ago you reached out to me on Reddit about Keystone.guru and the possibility to collab in one way or another. As I mentioned there I didn't see any way we could do it. However, I've been working on a redesign for the past ~2 months, and a user of my site has made a suggestion to include tier lists per dungeon by affix on the new site. I quite like this idea and perhaps it would be a nice way for us to work together.

The information would be displayed somewhere here: https://redesign.keystone.guru/routes. I'd make it something like `This week: S tier - data by mplus.subcreation.net`. Either way, if you'd like this idea I would need some sort of API to poll the data from so that I can display it on the site.

No rush - let me know if you're interested :)

**Comment by alcaras** [comment]
Heya! Thanks for submitting this issue -- I've had this on the todo list for a while.

Awesome idea!

I've put together a simple API with the dungeon ease tier list for the current set of affixes:
http://subcreation.net/api/v0/dungeon_ease_tier_list

This should update every 8 hours (alongside the site updates)

Let me know if you have any suggestions / questions / ideas for improvement!

**Comment by alcaras** [comment]
Also added a few more:
https://subcreation.net/api/v0/mplus_spec_tier_list

https://subcreation.net/api/v0/affixes_ease_tier_list

come by the site discord’s the #api channel if you like — using that as documentation for now

subc discord: https://discord.gg/X8dyq67
