### ISSUE TITLE
Main navbar links to castle-nathria from the pvp page, but links to raid on all other pages.

### ISSUE THREAD

**Issue by EthanGraber** [alcaras/mplus.subcreation.net#12]
Expected behavior, when on mplus.subcreation.net:
![image](https://user-images.githubusercontent.com/18070053/125331439-fccc5500-e315-11eb-9ee6-c4ea715eb987.png)

Incorrect behavior, when on pvp.subcreation.net:
![image](https://user-images.githubusercontent.com/18070053/125331498-0e156180-e316-11eb-952c-a4532f250091.png)

**Comment by alcaras** [comment]
Thanks! Will fix with tomorrow's update.

**Comment by alcaras** [comment]
Fixed now.
