### ISSUE TITLE
Conduit builds only shows 5 conduits instead of 6

### ISSUE THREAD

**Issue by ntowle** [alcaras/mplus.subcreation.net#13]
Pretty much everyone has 6 conduits now, and clicking through to the actual WCL page for the top run shows 6 conduits, yet only 5 are displayed in the "Conduit Builds" section.

Unsure if this is an issue with the WCL API or not.

**Comment by alcaras** [comment]
Alas, yes, it is an WCL API issue. WCL says it will be fixed with the next raid tier.

**Comment by alcaras** [comment]
This is now fixed in the WCL API for new logs. Subcreation will update as new logs replace old ones, and you'll see six conduits in more places.
