### ISSUE TITLE
Conduit Max key showing incorrectly

### ISSUE THREAD

**Issue by Seyona** [alcaras/mplus.subcreation.net#7]
https://mplus.subcreation.net/retribution-paladin.html#Conduits

A few conduits are showing with a lower Max key than their counter parts in Conduit Builds. 

IE Ringing Clarity shows up with a Max Key of +15, but there is a Conduit Build that uses it that has completed an 18. 

-----------

Unrelated to the issue, but how would one run this project locally if they would like to contribute?

**Comment by alcaras** [comment]
Thanks for the report! Will investigate. Not sure what's causing that right now, as the +15 max key doesn't even have a ret paladin in the log.

Re: contributing: You'll need to download the Google App Engine SDK and then run dev_appserver.py ./ in the main directory where you cloned the repository.

Once you do that, you'll need to initialize with data, for example by visiting http://localhost:8080/test/affixes. That'll get raider.io API data. For WCL data, you'll need an API key and create an auth.py file that sets api_key to it. Once you do that, you can run http://localhost:8080/test/dungeons and http://localhost:8080/test/raids to get Top Builds data for Havoc DH (or whatever you set in the TestWCLGetRankings https://github.com/alcaras/mplus.subcreation.net/blob/master/mplus.py#L2562 or TestWCLGetRankingsRaid further down.

**Comment by alcaras** [comment]
This is now fixed.
