### ISSUE TITLE
[Feature] Race per class / spec

### ISSUE THREAD

**Issue by lorem-ipsum-dolor-sit** [alcaras/mplus.subcreation.net#8]
Is it possible to add which race is used on the different specs?

**Comment by alcaras** [comment]
Unfortunately not at this time; not in the raider.io or WCL APIs :-/

**Comment by lorem-ipsum-dolor-sit** [comment]
mhh weird, cause the raider.io api has races included.

just a response snipped from the tryout option on https://raider.io/api#/mythic_plus/getApiV1MythicplusRuns
```json
...
"race": {
                "id": 8,
                "name": "Troll",
                "slug": "troll",
                "faction": "horde"
              },
...
```

**Comment by alcaras** [comment]
Didn't realize that got added. Thank you for pointing it out!

Will look into it, though I imagine since I'd put races into Top Builds, the critical API here is WCL :-/

**Comment by lorem-ipsum-dolor-sit** [comment]
It is Possible with: https://www.warcraftlogs.com/v2-api-docs/warcraft/character.doc.html

```graphql
{
  characterData 
  {
    character(id: 123456) 
    {
	gameData
    }
  }
}
```

**Comment by alcaras** [comment]
Thank you; It's not in the rankings api which is what the site uses, as crawling 400k+ logs individually would be prohibitive. (The site is also still on the legacy v1 API, fwiw).

**Comment by alcaras** [comment]
That said, you can find a race breakdown (for at least M+ and PvP) on wowvalor.app
