### ISSUE TITLE
Support Heroic mode for Raids

### ISSUE THREAD

**Issue by andybergon** [alcaras/mplus.subcreation.net#9]
Mythic raids, especially at the beginning of a tier, have very few entries and sometimes even fights with major differences. It would be useful to support parsing Heroic raids to have a different view, maybe even more useful for some users.

@alcaras

**Comment by alcaras** [comment]
Thanks for the suggestion! Will work on getting this functionality back in and will update this issue once it’s in.

**Comment by alcaras** [comment]
This is now supported, including Heroic Tier Lists and Heroic Top Builds.
